---
title: "stat-comp-hwk-4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1a
```{r num1a}
library("tidyverse"); library("extrafont")
theme_set(theme_minimal(base_family = "Roboto Condensed"))
theme_update(panel.grid.minor = element_blank())
ggplot(diamonds, aes(carat)) +
  geom_histogram(bins = 30) +
  geom_freqpoly(color = 'red', bins = 30) +
  geom_point(stat="bin" , bins = 30 , color ="red") +
  scale_x_continuous(minor_breaks = NULL) +
  scale_y_continuous(minor_breaks = NULL) +
  theme_minimal()

```
## Question 1b
```{r}
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  ggplot2.discrete.colour = "brewer",
  ggplot2.discrete.fill = "brewer")
library(patchwork)
library(tidyverse)
x <- seq(0,2*pi,length.out = 500)
y <- seq(0,2*pi,length.out = 500)
f <- function(x,y){
 1/2*(sin(2*x) + sin(2*y))
}
df <- expand.grid(x=x, y=y)
value <- vector()
for (i in seq_along(df$x)) {
 value[i] = f(df$x[i],df$y[i])  
}
df$value <- value
p1 = ggplot(df, aes(x,y))+
      geom_raster(aes(fill= value),interpolate = TRUE) +
      scale_fill_continuous(name = "f(x,y)" ) +
      theme_minimal() +
      scale_x_continuous(breaks = c(0, pi/2, pi, 3*pi/2, 2*pi),
      label = c(0, expr(pi / 2), expression(pi), expr(3 * pi / 2), expr(2 * pi)),
      minor_breaks = NULL) +
      scale_y_continuous(breaks = c(0, pi/2, pi, 3*pi/2, 2*pi),
      label = c(0, expr(pi / 2), expression(pi), expr(3 * pi / 2), expr(2 * pi)),
      minor_breaks = NULL) +
      coord_equal()
     
p2 = ggplot(df,aes(x,y,z = value)) +
      geom_contour(aes(colour = after_stat(nlevel))) +
      theme_minimal() +
      scale_x_continuous(breaks = c(0, pi/2, pi, 3*pi/2, 2*pi),
      label = c(0, expr(pi / 2), expression(pi), expr(3 * pi / 2), expr(2 * pi)),
      minor_breaks = NULL) +
      scale_y_continuous(breaks = c(0, pi/2, pi, 3*pi/2, 2*pi),
      label = c(0, expr(pi / 2), expression(pi), expr(3 * pi / 2), expr(2 * pi)),
      minor_breaks = NULL) +
      scale_colour_continuous(name = "f(x,y)") +
      coord_equal()
p1 + p2
```

## Question 1c
```{r}
df <- data.frame(x = 1:5, y = 1:5)
dens_df<- data.frame(expand.grid(x = MASS::kde2d(df$x,df$y)$x,y = MASS::kde2d(df$x,df$y)$y),
                     density = as.vector(MASS::kde2d(df$x,df$y)$z)
                      )
ggplot() +
  geom_raster(data=dens_df,aes(x,y, fill=density), interpolate = TRUE) +
  geom_point(data=df,aes(x,y), color = "red", size = 4) +
  theme_minimal() +
  scale_x_continuous(limits = c(0, 6), minor_breaks = NULL) +
  scale_y_continuous(limits = c(0, 6), minor_breaks = NULL) +
  coord_equal()
```


## Question 2a
```{r num2a}
dot <- function(x,y) {
  z <- c()
  for (i in 1:length(x)) {
    z <- c(z, x[i]*y[i])
  }
  z  
}

norm <- function(c) {
  total <- 0
  for (j in 1:length(c)) {
    total <- total + dot(c[j],c[j])
  }
  sqrt(total)
}

normalize <- function(v) {
  v / norm(v)
}

is_zero <- function(x) {
  norm(x) <= .Machine$double.eps
}

# Projects y onto x
project_onto <- function(y,x) {
  if (is_zero(x)) {
    c(0,0)
  } else {
  (dot(y,x)/norm(x)^2)*x
  }
}

emax <- function(A, tol) {
  dif <- 1
  v <- matrix (c(1:3), nrow = 3)
  
  # The while loop runs until the difference betwen consecutive iterations
  # falls below a particular threshhold
  while (dif > tol) {
    old_v <- v
    v <- normalize(A %*% v)
    v <- sign(v[1]) * v
    dif <- max(abs(v - old_v))
  }
  #Zeros out values that are effectively zero
  vector <- replace(v, v < 10 ^ - 6, 0)
  value <- t(v) %*% A %*% v

  print("$values$")
  print(value)
  print("$vector")
  print(t(vector))
}

A <- matrix (c(1:4, 6:10), nrow = 3, byrow = TRUE)
tol <-  sqrt(.Machine$double.eps)

emax(A, tol)

eigen(A)

emax(-A, tol)
```


## Question 2b

```{r}
dot <- function(x, y){
  if (length(x) != length(y)) stop("vectors `x` and `y` are not of the same length.")
  # loop over the vector, accumulating the inner product
  out <- 0
  for (i in seq_along(x)) out <- out + x[i]*y[i]
  # return inner product
  out
}
norm <- function(x) sqrt(dot(x, x))
make_positive <- function(x) sign(x[1]) * x
make_first_row_positive <- function(A) apply(A, 2, make_positive)
eigen_qr <- function(A, tol = sqrt(.Machine$double.eps)) {
  A_0 <- A
  U_0 <- diag(nrow = nrow(A))
  Q_0 <- qr.Q(qr(A))
  R_0 <- qr.R(qr(A))
  A_1 <- R_0 %*% Q_0
  U_1 <- make_first_row_positive(U_0 %*% Q_0)
  i<- 0 
  while ((norm(A_1-A_0)) > tol) {
    A_0 <- A_1
    U_0 <- U_1
    A_1 <- qr.R(qr(A_0)) %*% qr.Q(qr(A_0))
    U_1 <- make_first_row_positive(U_0 %*% qr.Q(qr(A_0))) 
    i = i + 1
  }
  values <- vector()
for (i in 1:nrow(A)) {
  values[i] <- A_1[i,i] 
}
 out <- list("values" = values, "vectore" = U_1)
 return(out)
}
(A <- matrix(c(1:4, 6:10), nrow = 3, byrow = TRUE))
(A <- crossprod(A))
eigen_qr(A)$values

```

## Question 2c
```{r}
det_qr <- function(A) {
  A <- eigen_qr(A)$values
  out <- 1
    for(i in 1:length(A)){
         out <- out*A[i]
    }
    out
}
set.seed(2)
(A <- matrix(rpois(64, lambda = 5), nrow = 8))
(A <- crossprod(A))
det_qr(A)
det(A)
```

